name: Tests

on:
  push:
  pull_request:

jobs:
  lint:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Run E2E tests
        run: ./e2e/run-e2e.sh